### ISSUE TITLE
Custom setup of TextFormatter

### ISSUE THREAD

**Issue by johnd0e** [phpBB-Studio/TextFormatter#3]
**Is your feature request related to a problem? Please describe.**
Currently in ACM there is very limited set of options.
I understand that it's impossible to add every available TextFormatter options, but some options are really necessary/helpful.

E.g., when I activate Litedown plugin - all text become too large.
<details><summary>See sample</summary>

![image](https://user-images.githubusercontent.com/1838643/73924482-3f922e00-48d5-11ea-828b-7cd040f0b783.png)
</details>

The issue is caused by additional paragraph wrapping, which I'd prefer to avoid.
And it's possible: I just need remove `ManageParagraphs` [rule generator](https://s9etextformatter.readthedocs.io/Rules/Rules_generators/).

**Describe the solution you'd like**
- Some additional control in ACP, e.g. editbox, where I could enumerate list of rules to disable/enable.
- Editbox, where I could put any additional code to customize TextFormatter setup.
  E.g. to resolve mentioned issue I'd put such code:
  <details>

  ```php
  $configurator->rulesGenerator->remove('ManageParagraphs');
  ```
  </details>

**Additional context**
There are a lot of other parameters we may want to customize.
E.g. add [predefined bbcodes](https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Add_from_the_repository/).
Or enhance templates:
<details><summary>Sample: implement title for markdown spoiler</summary>

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->Litedown;
$configurator->tags['spoiler']->template = '<details>
	<xsl:if test="name(*[1]) = \'H1\'">
		<summary><xsl:value-of select="*[1]"/></summary>
	</xsl:if>
	<xsl:apply-templates/>
</details>';

extract($configurator->finalize());

$text = '>! # Title
>!
>! Content';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
<details><summary>Title</summary><h1>Title</h1>

<p>Content</p></details>
```

</details>

**Comment by 3D-I** [comment]
All Markdown deployments surround the text in paragraph tags.
An option in ACP can be done but is far beyond the scope of this project IMO.

About the `details (spoiler)` we helped the development of the its bbcode with no JS validated at phpBB.com, see: https://www.phpbb.com/customise/db/bbcode/spoiler_no_js/ and the related https://www.phpbb.com/community/viewtopic.php?f=438&t=2531861 discussion topic.

**Comment by johnd0e** [comment]
> All Markdown deployments surround the text in paragraph tags.

Well, I can't speak for 'All', but I will be happy without paragraphs.

> An option in ACP can be done but is far beyond the scope of this project IMO.

Then you should address large text issue in some other way.
And I cannot agree about extension scope: from what I see in README.MD, you promise administrator the "full power" of TextFormatter. Definitely it's impossible without additional configuration.

> About predefined bbcodes from repository that's also not something related to this extension.

But we are speaking about TextFormatter's repository, for me it is closely related to this extension,


> About the `details (spoiler)` we helped the development of the its bbcode with no JS

I saw that. But try spoiler in markdown syntax: https://s9etextformatter.readthedocs.io/Plugins/Litedown/Syntax/#spoilers

Unfortunately it does not include Title for spoiler. But it could be fixed via template, see my sample.

**Comment by 3D-I** [comment]
The real scope of this extension is to: 

**easily enable / disable any plugin and optimise your custom BBCodes.**

**Comment by johnd0e** [comment]
Well, I agree that it's your right - to define own extension's scope)
But without configuration it's much less useful.

Then I will consider another alternative - to make some primitive custom extension, without any UI.
May be you could advise me where should I start?

Currently I know nothing about phpBB extensions. But I see https://phpbbstudio.com/skeleton.
Could you tell which options should I check? Is it enough to choose only **PHP event listeners** if I only need to make setup in code (without any UI)?

**Comment by 3D-I** [comment]
That's pretty easy, fork this repository and modify it to fit your needs.

Also, we offer custom coding on a per request basis at our own site if you are interested.

Locking as such.

**Comment by johnd0e** [comment]
> E.g., when I activate Litedown plugin - all text become too large.

@3D-I 
So you believe that large text is not an issue?

**Comment by 3D-I** [comment]
> So you believe that large text is not an issue?

As I said the scope of this extension is to _easily enable / disable any plugin and optimise your custom BBCodes_. We didn't make that plugin therefore you should address this question to the people that made it. 

Another option is to ask for customisations at our website as I said multiple times.
I hope all points are clear now, that's all.

Best regards.

**Comment by 3D-I** [comment]
Moreover I noticed you seem to have the same issue with another extension as per
https://www.phpbb.com/customise/db/extension/markdown/support/topic/208621
You got the same answer as mine, more or less. ;)

**Comment by johnd0e** [comment]
I do not see here any point to argue, but if you want to discuss..

> You got the same answer as mine, more or less. ;-)

Actually not.

(1)
Mentioned extension is functionally solid, it is focused on single feature (litedown), and trying to do it best.
It's author though is open to new propositions.
He refuses to remove ManageParagraps rule because of his strong belief that markdown must have paragraphs.
Explaining why I disagree would be offtopic here, but because of this I am looking for alternatives.

(2)
You extension has much more general purpose. And more configuration options mean that it can be even more useful.
I open this issue in belief that proposed enhancement can fit it to more cases.
It's ok that you are not going to implement it yourself, but honestly I was surprised that you has closed the issue completely.
I'd rather keep it open, may be someone will implement that in future.
So I do not understand your point of limiting your extension to narrowest scope.

(3)
I haven't asked here to remove ManageParagraphs rule generator.
I've just wrote that it looks for me like good idea - add a possibility to toggle arbitrary rules in general.
Or even less specific - execute arbitrary actions TextFormatter\Configurator via custom php code.

> Another option is to ask for customisations at our website as I said multiple times.

Yes, I've heard. I understand that it's your business, and appreciate that.
But what I am trying to do here is not connected to any business. I do it for fun.
Studying new things, communicating with other developers, reporting bugs, and proposing new features.

**Comment by 3D-I** [comment]
Your request has not been approved. Thanks.

**Comment by mrgoldy** [comment]
The problem is, is that we can not simply provide an interface for tag rules.
The 'rules generator' you list, are all rules that are available on a *per tag basis*.
Meaning, they are not global settings, but per specific element such as a BBCode.
We can not control how paragraphs are build with text, nor do we have any control over how plugins handle the mark up/formatting of text.

This extension just allows you to enable / disable plugins that are available.
Additionally we provide some template parameters that can be used within Custom BBCodes.
Custom BBCodes created by the Administrator and not by this extension.

As soon as we start adding custom BBCodes, there is no stop it.
Aswell as we're just asking for conflicts with other extensions at that point.

If there are any issues with the plugin(s), you're best of reporting them to JoshyPHP, the author of the s9e TextFormatter.

**Comment by johnd0e** [comment]
> The problem is, is that we can not simply provide an interface for tag rules.
> The 'rules generator' you list, are all rules that are available on a _per tag basis_.

Actually not, they are shared, see https://s9etextformatter.readthedocs.io/Rules/Automatic_rules_generation/

> As soon as we start adding custom BBCodes, there is no stop it.

See https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Add_from_the_repository/
There is **limited** list of predefined bbcodes.
I do not mean to add them all, but it'd be useful to be able to choose some (e.g. just enter their list into editbox).

> If there are any issues with the plugin(s), you're best of reporting them to JoshyPHP, the author of the s9e TextFormatter.

s9e/TextFormatter is general purpose library, which is necessary to fine-tune for any particular case.
That additional configuration supposed to be just some php code.
So there is no issue with s9e/TextFormatter.

But your phpBB-Studio / TextFormatter is extension for phpBB, which supposed to be configured via UI.
I understand that it's impossible to has UI option for every single TextFormatter feature.
So one of alternative ways (that I've named in my initial message) would be to allow configuration in form of user-defined php code.

Well, you've rejected my idea, and that's ok for me.
But note, that currently your extension's `Litedown` option is barely-usable.
Have you tried to enable it?
Doesn't that font look too large for you?

**Comment by mrgoldy** [comment]
That's just simply not true..
The rules are still on a per tag basis, so you can not configure them globally.

I know there is a list of predefined BBCodes, but if we enable them, we might be overriding already added BBCodes. Not to mention, that there are already other extensions out there that allow you to enable the standard BBCodes from the s9e repository.

We do use this extension in a different capacity ourselves, and we have no issues with it.
We know how the s9e Library works and what is possible and what is not, that's why we made this extension to begin with. This will open up alot of possibilities.

If you do not want to use it as is, that's fine. 
If you want to use it in a different capacity, that's fine aswell and you can modify it yourself to your liking. But please stop posting untruths and contradictions.
