### ISSUE TITLE
Implement permission to access TextFormatter settings in ACP

### ISSUE THREAD

**Issue by johnd0e** [phpBB-Studio/TextFormatter#4]
**Is your feature request related to a problem? Please describe.**
Currently only administrator can setup TextFormatter.
I'd like to allow some moderator to make setup, but it is not secure now, as it requires too broad permissions set.

**Describe the solution you'd like**
I'd like to have special permission, that could be granted independently.

**Comment by 3D-I** [comment]
That's something we will not implement.
